server:
  port: 9090

spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    url: jdbc:hsqldb:file:testdb
    username: sa
    password:
    dirver-class-name: org.hsqldb.jdbc.JDBCDriver
    # HikariCP配置:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000

session:
  forbidden:
    url:
      suffixes: jpg,js,css,gif,png,ico,swf,otf,svg,eot,ttf,woff,map

pebble:
  suffix:
  cache: false

demo:
  domain: localhost