spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_shiro?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Aijie821418.
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false # 禁用模板引擎编译的缓存结果。由热部署来实现，更改代码后，使用 Ctrl+F9(IDEA) 更新
    mode: LEGACYHTML5 # 避免 thymeleaf 对 html 文件的严格校验（如检查标签必须对称等）

  # 使用 jpa 技术，运行实体代码自动生成数据表
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 9090
